const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { randomUUID } = require("node:crypto");
const { sourceFingerprint, needsBuild } = require("../scripts/production-build.cjs");

test("production fingerprints detect changed, added and absent sources while ignoring generated type references", () => {
  const fixture = path.join(__dirname, "..", ".cache", "qa", `build-${randomUUID()}`);
  fs.mkdirSync(path.join(fixture, "src"), { recursive: true });
  fs.writeFileSync(path.join(fixture, "src", "app.ts"), "const version = 1;");
  fs.writeFileSync(path.join(fixture, "tsconfig.json"), JSON.stringify({ include: ["**/*.ts", ".next/types/**/*.ts"] }));
  const original = sourceFingerprint(fixture);
  assert.equal(needsBuild(fixture), true);
  fs.mkdirSync(path.join(fixture, ".cache", "production", "standalone"), { recursive: true });
  fs.writeFileSync(path.join(fixture, ".cache", "production", "BUILD_ID"), "build-1");
  fs.writeFileSync(path.join(fixture, ".cache", "production", "standalone", "server.js"), "fixture");
  fs.writeFileSync(path.join(fixture, ".cache", "production-source.json"), JSON.stringify({ fingerprint: original, buildId: "build-1" }));
  assert.equal(needsBuild(fixture), false);
  fs.writeFileSync(path.join(fixture, "tsconfig.json"), JSON.stringify({ include: ["**/*.ts", ".next/types/**/*.ts", ".cache/production/types/**/*.ts"] }));
  assert.equal(sourceFingerprint(fixture), original);
  assert.equal(needsBuild(fixture), false);
  fs.writeFileSync(path.join(fixture, "next-env.d.ts"), "Generated type reference");
  assert.equal(sourceFingerprint(fixture), original);
  fs.writeFileSync(path.join(fixture, "src", "app.ts"), "const version = 2;");
  assert.notEqual(sourceFingerprint(fixture), original);
  assert.equal(needsBuild(fixture), true);
  fs.writeFileSync(path.join(fixture, "src", "app.ts"), "const version = 1;");
  assert.equal(sourceFingerprint(fixture), original);
  fs.writeFileSync(path.join(fixture, "src", "added.ts"), "New source");
  assert.notEqual(sourceFingerprint(fixture), original);
  assert.equal(needsBuild(fixture), true);
  fs.writeFileSync(path.join(fixture, ".cache", "production", "BUILD_ID"), "different-build");
  assert.equal(needsBuild(fixture), true);
});
